remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Target Speech Separation with Dual-Path RNN]
description: [Tiny demo for my bachelor thesis "Target Speech Separation with Dual-Path RNN"]
