---
name: generate_datasets

data:
  dataset_type: LibrimixSpe 
  train_path:
  eval_path:
  test_path: ../../Libri2Mix/wav8k/min/metadata/mixture_test_mix_clean.csv
  nrows_train:
  nrows_test: 150
  nrows_eval:
  segment: 3
  n_src: 2

save_path:
  train:
  eval:
  test: ../../datasets/test_set_spe_tiny.pkl

sample_rate: 8000