---
name: generate_datasets

data:
  dataset_type: LibrimixSpe 
  train_path: ../../Libri2Mix/wav8k/min/metadata/mixture_train-100_mix_clean.csv
  eval_path: ../../Libri2Mix/wav8k/min/metadata/mixture_dev_mix_clean.csv
  test_path: ../../Libri2Mix/wav8k/min/metadata/mixture_test_mix_clean.csv
  nrows_train: 1000
  nrows_test: 200
  nrows_eval: 200
  segment: 3

save_path:
  train: ../../datasets/train_set_spe_small.pkl
  eval: ../../datasets/eval_set_spe_small.pkl
  test: ../../datasets/test_set_spe_small.pkl

sample_rate: 8000