---
name: generate_datasets

data:
  train_path: ../../Libri2Mix/wav8k/min/metadata/mixture_train-100_mix_clean.csv
  eval_path: ../../Libri2Mix/wav8k/min/metadata/mixture_dev_mix_clean.csv
  test_path: ../../Libri2Mix/wav8k/min/metadata/mixture_test_mix_clean.csv
  nrows_train: 13900
  nrows_test: 3000
  nrows_eval: 3000
  segment: 3

save_path:
  train: ../../datasets/train_set.pkl
  eval: ../../datasets/eval_set.pkl
  test: ../../datasets/test_set.pkl

sample_rate: 8000