---
name: MiniTrain

data:
  train_path: Libri2Mix/wav8k/min/metadata/mixture_train-100_mix_clean.csv
  valid_path: Libri2Mix/wav8k/min/metadata/mixture_dev_mix_clean.csv
  nrows_train: 1
  nrows_valid: 1
  segment: 3

training:
  num_workers: 4
  batch_size: 1

model:
  _target_: src.models.dprnn.DPRNNTasNet
  input_size: 64
  output_size: 64
  feature_size: 128
  hidden_size: 128
  chunk_length: 250
  kernel_size: 2
  hop_length: 125
  n_repeats: 6
  bidirectional: True
  norm_type: ln
  activation_type: sigmoid
  dropout: 0

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: !!float 1e-5

lr_scheduler:
  patience: 5
  factor: 0.5
  decay_rate: null

logs:
  metadata: 
    ids:
      - 0
  wandb_credentials:
    wandb_project: DPRNN-TasNet
    wandb_entity: aleksashka
    wandb_key: d9c095aeb842cfdea791b21bc5ed65a02e4e6af5
    run_name: report

print_freq: 1
clip_norm: 5
epochs: 1
early_stop: 100
sample_rate: 8000
is_metrics: False

checkpoint_path: null
n_checkpoints: 100
new_checkpoints_path: ./chkpts
