---
name: train

data:
  use_generated_train: ../../datasets/train_set.pkl
  use_generated_eval: ../../datasets/eval_set.pkl
  train_path: 
  eval_path:
  nrows_train:
  nrows_eval:
  segment:
  num_workers: 2
  batch_size: 5

model:
  _target_: src.models.dprnn.DPRNNTasNet
  input_size: 64
  output_size: 64
  feature_size: 128
  hidden_size: 128
  chunk_length: 250
  kernel_size: 2
  hop_length: 125
  n_repeats: 6
  bidirectional: True
  norm_type: ln
  activation_type: sigmoid
  dropout: 0

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0005
  weight_decay: !!float 1e-5

lr_scheduler:
  patience: 5
  factor: 0.5
  decay_rate: null

logs:
  metadata: 
    ids:
      - 14
      - 516
      - 2901
  wandb_credentials:
    wandb_project: DPRNN-TasNet
    wandb_entity: aleksashka
    wandb_key: 
    run_name: report

print_freq: 5
clip_norm: 5
cur_epoch: 29
epochs: 60
early_stop: 100
sample_rate: 8000
is_metrics: False

checkpoint_path: ../../chkpts/best_checkpoint_20-04_4.pt
n_checkpoints: 1000
new_checkpoints_path: ../../chkpts