---
name: MiniTrain

model:
  _target_: src.models.dprnn.DPRNNTasNet
  input_size: 64
  output_size: 64
  feature_size: 128
  hidden_size: 128
  chunk_length: 250
  kernel_size: 2
  hop_length: 125
  n_repeats: 6
  bidirectional: True
  norm_type: ln
  activation_type: sigmoid
  dropout: 0

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: !!float 1e-5

lr_scheduler:
  patience: 5
  factor: 0.5
  decay_rate: 0.96

logs:
  metadata: 
    ids:
      - 0
      - 1
  wandb_credentials:
    wandb_project: DPRNN-TasNet
    wandb_entity: aleksashka
    wandb_key: 
    run_name: report

print_freq: 1
clip_norm: 5
epochs: 10
early_stop: 100
sample_rate: 8000
batch_size: 2
is_metrics: False

checkpoint_path: null
n_checkpoints: 100
new_checkpoints_path: ./chkpts