---
name: DPRNNTasNetTest

device: cpu

model:
  _target_: src.models.dprnn.DPRNNTasNet
  input_size: 64
  output_size: 64
  feature_size: 128
  hidden_size: 128
  chunk_length: 250
  kernel_size: 2
  hop_length: 125
  n_repeats: 6
  bidirectional: True
  dropout: 0